// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ColumnInfo {
    "name": string;
    "dataType": string;
    "isNullable": boolean;
    "isPrimary": boolean;
    "isForeign": boolean;
    "foreignTable"?: string;
    "foreignColumn"?: string;
    "defaultVal"?: string;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("isNullable" in $$source)) {
            this["isNullable"] = false;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("isForeign" in $$source)) {
            this["isForeign"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

export class ConnectionConfig {
    "id": string;
    "name": string;
    "driver": DriverType;
    "color": string;
    "folderId"?: string;

    /**
     * SQLite
     */
    "filePath"?: string;

    /**
     * PostgreSQL / MySQL / MariaDB
     */
    "host"?: string;
    "port"?: number;
    "database"?: string;
    "username"?: string;
    "password"?: string;
    "sslMode"?: string;
    "schema"?: string;

    /**
     * Statement-level gate only - does not block side-effecting functions inside SELECT (e.g. pg_terminate_backend).
     * Pair with a restricted DB role for hard isolation.
     */
    "readOnly"?: boolean;

    /**
     * SSH tunnel (PostgreSQL / MySQL / MariaDB). Host/Port above are resolved from the bastion.
     */
    "ssh"?: SSHConfig;

    /** Creates a new ConnectionConfig instance. */
    constructor($$source: Partial<ConnectionConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = DriverType.$zero;
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionConfig {
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField14_0($$parsedSource["ssh"]);
        }
        return new ConnectionConfig($$parsedSource as Partial<ConnectionConfig>);
    }
}

export class ConnectionStatus {
    "connected": boolean;
    "database": string;
    "schema": string;
    "user": string;
    "host"?: string;

    /** Creates a new ConnectionStatus instance. */
    constructor($$source: Partial<ConnectionStatus> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus($$parsedSource as Partial<ConnectionStatus>);
    }
}

export enum DriverType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DriverSQLite = "sqlite",
    DriverPostgres = "postgres",

    /**
     * MariaDB uses the same driver
     */
    DriverMySQL = "mysql",
};

export class HistoryEntry {
    "id": string;
    "connectionId": string;
    "sql": string;
    "executedAt": string;
    "durationMs": number;
    "success": boolean;
    "error"?: string;

    /** Creates a new HistoryEntry instance. */
    constructor($$source: Partial<HistoryEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("executedAt" in $$source)) {
            this["executedAt"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry($$parsedSource as Partial<HistoryEntry>);
    }
}

export class QueryResult {
    "columns": string[];
    "columnTypes": string[];
    "rows": any[][];
    "rowCount": number;
    "affectedRows": number;
    "durationMs": number;
    "message"?: string;
    "primaryKeys"?: string[];
    "tableName"?: string;
    "schemaName"?: string;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("columnTypes" in $$source)) {
            this["columnTypes"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("affectedRows" in $$source)) {
            this["affectedRows"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("columnTypes" in $$parsedSource) {
            $$parsedSource["columnTypes"] = $$createField1_0($$parsedSource["columnTypes"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        if ("primaryKeys" in $$parsedSource) {
            $$parsedSource["primaryKeys"] = $$createField7_0($$parsedSource["primaryKeys"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class RowDelete {
    "schema": string;
    "table": string;
    "primaryKeys": { [_ in string]?: any }[];

    /** Creates a new RowDelete instance. */
    constructor($$source: Partial<RowDelete> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("primaryKeys" in $$source)) {
            this["primaryKeys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowDelete instance from a string or object.
     */
    static createFrom($$source: any = {}): RowDelete {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryKeys" in $$parsedSource) {
            $$parsedSource["primaryKeys"] = $$createField2_0($$parsedSource["primaryKeys"]);
        }
        return new RowDelete($$parsedSource as Partial<RowDelete>);
    }
}

export class RowUpdate {
    "schema": string;
    "table": string;
    "primaryKey": { [_ in string]?: any };
    "changes": { [_ in string]?: any };

    /** Creates a new RowUpdate instance. */
    constructor($$source: Partial<RowUpdate> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = {};
        }
        if (!("changes" in $$source)) {
            this["changes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): RowUpdate {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryKey" in $$parsedSource) {
            $$parsedSource["primaryKey"] = $$createField2_0($$parsedSource["primaryKey"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField3_0($$parsedSource["changes"]);
        }
        return new RowUpdate($$parsedSource as Partial<RowUpdate>);
    }
}

export enum SSHAuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SSHAuthPassword = "password",
    SSHAuthKey = "key",
    SSHAuthAgent = "agent",
};

export class SSHConfig {
    "enabled"?: boolean;
    "host"?: string;
    "port"?: number;
    "username"?: string;
    "auth"?: SSHAuthMethod;
    "password"?: string;
    "keyPath"?: string;
    "passphrase"?: string;

    /**
     * KnownHosts overrides the default ~/.ssh/known_hosts.
     */
    "knownHosts"?: string;

    /**
     * IgnoreHostKey accepts any bastion key, leaving the hop open to interception.
     */
    "ignoreHostKey"?: boolean;

    /** Creates a new SSHConfig instance. */
    constructor($$source: Partial<SSHConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfig($$parsedSource as Partial<SSHConfig>);
    }
}

export class SavedQuery {
    "id": string;
    "name": string;
    "connectionId"?: string;
    "sql": string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new SavedQuery instance. */
    constructor($$source: Partial<SavedQuery> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedQuery($$parsedSource as Partial<SavedQuery>);
    }
}

export class SchemaBundle {
    "status": ConnectionStatus;
    "schemas": SchemaInfo[];
    "loadedTables": SchemaTables[];

    /** Creates a new SchemaBundle instance. */
    constructor($$source: Partial<SchemaBundle> = {}) {
        if (!("status" in $$source)) {
            this["status"] = (new ConnectionStatus());
        }
        if (!("schemas" in $$source)) {
            this["schemas"] = [];
        }
        if (!("loadedTables" in $$source)) {
            this["loadedTables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaBundle instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaBundle {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        if ("schemas" in $$parsedSource) {
            $$parsedSource["schemas"] = $$createField1_0($$parsedSource["schemas"]);
        }
        if ("loadedTables" in $$parsedSource) {
            $$parsedSource["loadedTables"] = $$createField2_0($$parsedSource["loadedTables"]);
        }
        return new SchemaBundle($$parsedSource as Partial<SchemaBundle>);
    }
}

export class SchemaInfo {
    "name": string;

    /** Creates a new SchemaInfo instance. */
    constructor($$source: Partial<SchemaInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SchemaInfo($$parsedSource as Partial<SchemaInfo>);
    }
}

export class SchemaTables {
    "schema": string;
    "tables": TableInfo[];

    /** Creates a new SchemaTables instance. */
    constructor($$source: Partial<SchemaTables> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaTables instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaTables {
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField1_0($$parsedSource["tables"]);
        }
        return new SchemaTables($$parsedSource as Partial<SchemaTables>);
    }
}

export class TableDataRequest {
    "schema": string;
    "table": string;
    "offset": number;
    "limit": number;
    "orderBy"?: string;
    "orderDir"?: string;
    "filter"?: string;

    /** Creates a new TableDataRequest instance. */
    constructor($$source: Partial<TableDataRequest> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDataRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TableDataRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableDataRequest($$parsedSource as Partial<TableDataRequest>);
    }
}

export class TableInfo {
    "schema": string;
    "name": string;
    "type": string;

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}

// Private type creation functions
const $$createType0 = SSHConfig.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ConnectionStatus.createFrom;
const $$createType7 = SchemaInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = SchemaTables.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = TableInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
