package database

import (
	"strings"
	"testing"
)

func TestRenderColumn(t *testing.T) {
	tests := []struct {
		name string
		col  DDLColumn
		want string
	}{
		{
			name: "plain nullable",
			col:  DDLColumn{Name: "email", Type: "text"},
			want: `"email" text`,
		},
		{
			name: "not null with default",
			col:  DDLColumn{Name: "created_at", Type: "timestamptz", NotNull: true, Default: "now()"},
			want: `"created_at" timestamptz DEFAULT now() NOT NULL`,
		},
		{
			name: "identity outranks default",
			col:  DDLColumn{Name: "id", Type: "bigint", NotNull: true, Identity: "BY DEFAULT", Default: "ignored"},
			want: `"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
		},
		{
			name: "generated column carries no default",
			col:  DDLColumn{Name: "total", Type: "numeric", Generated: "qty * price", Default: "ignored"},
			want: `"total" numeric GENERATED ALWAYS AS (qty * price) STORED`,
		},
		{
			name: "explicit collation",
			col:  DDLColumn{Name: "name", Type: "text", Collation: "C"},
			want: `"name" text COLLATE "C"`,
		},
		{
			name: "embedded quote is escaped",
			col:  DDLColumn{Name: `we"ird`, Type: "text"},
			want: `"we""ird" text`,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := RenderColumn(DriverPostgres, tc.col); got != tc.want {
				t.Errorf("RenderColumn()\n got %s\nwant %s", got, tc.want)
			}
		})
	}
}

func TestComposeCreateTable(t *testing.T) {
	got := ComposeCreateTable(DriverPostgres, "public", "users",
		[]DDLColumn{
			{Name: "id", Type: "bigint", NotNull: true, Identity: "BY DEFAULT"},
			{Name: "email", Type: "text", NotNull: true},
		},
		[]string{`CONSTRAINT "users_pkey" PRIMARY KEY ("id")`})

	want := `CREATE TABLE "public"."users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" text NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);`
	if got != want {
		t.Errorf("ComposeCreateTable()\n got %s\nwant %s", got, want)
	}
}

func TestComposeCreateTableMySQLQuoting(t *testing.T) {
	got := ComposeCreateTable(DriverMySQL, "shop", "orders",
		[]DDLColumn{{Name: "id", Type: "int", NotNull: true}}, nil)
	if !strings.Contains(got, "`shop`.`orders`") || !strings.Contains(got, "`id` int NOT NULL") {
		t.Errorf("MySQL DDL should use backticks, got %s", got)
	}
}

func TestComposeCreateTableEmpty(t *testing.T) {
	got := ComposeCreateTable(DriverPostgres, "public", "empty", nil, nil)
	if got != `CREATE TABLE "public"."empty" ();` {
		t.Errorf("empty table DDL = %s", got)
	}
}

func TestRenderConstraint(t *testing.T) {
	tests := []struct {
		name string
		in   ConstraintInfo
		want string
	}{
		{
			name: "engine definition wins over synthesis",
			in:   ConstraintInfo{Name: "ck_age", Type: "CHECK", Definition: "CHECK ((age > 0))"},
			want: `CONSTRAINT "ck_age" CHECK ((age > 0))`,
		},
		{
			name: "synthesized primary key",
			in:   ConstraintInfo{Name: "users_pkey", Type: "PRIMARY KEY", Columns: []string{"id"}},
			want: `CONSTRAINT "users_pkey" PRIMARY KEY ("id")`,
		},
		{
			name: "synthesized composite unique",
			in:   ConstraintInfo{Name: "u_ab", Type: "UNIQUE", Columns: []string{"a", "b"}},
			want: `CONSTRAINT "u_ab" UNIQUE ("a", "b")`,
		},
		{
			name: "synthesized foreign key",
			in: ConstraintInfo{
				Name: "fk_org", Type: "FOREIGN KEY", Columns: []string{"org_id"},
				RefTable: "orgs", RefColumns: []string{"id"},
			},
			want: `CONSTRAINT "fk_org" FOREIGN KEY ("org_id") REFERENCES "orgs" ("id")`,
		},
		{
			name: "unnamed constraint drops the CONSTRAINT prefix",
			in:   ConstraintInfo{Type: "PRIMARY KEY", Columns: []string{"id"}},
			want: `PRIMARY KEY ("id")`,
		},
		{
			name: "check without definition is skipped",
			in:   ConstraintInfo{Name: "ck", Type: "CHECK"},
			want: "",
		},
		{
			name: "primary key without columns is skipped",
			in:   ConstraintInfo{Name: "pk", Type: "PRIMARY KEY"},
			want: "",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := RenderConstraint(DriverPostgres, tc.in); got != tc.want {
				t.Errorf("RenderConstraint()\n got %q\nwant %q", got, tc.want)
			}
		})
	}
}

func TestRenderCreateIndex(t *testing.T) {
	tests := []struct {
		name   string
		driver DriverType
		in     IndexInfo
		want   string
	}{
		{
			name:   "unique index with method",
			driver: DriverPostgres,
			in: IndexInfo{
				Name: "users_email_idx", Schema: "public", Table: "users",
				Columns: []string{"email"}, IsUnique: true, Method: "btree",
			},
			want: `CREATE UNIQUE INDEX "users_email_idx" ON "public"."users" USING btree ("email");`,
		},
		{
			name:   "mysql drops the method",
			driver: DriverMySQL,
			in: IndexInfo{
				Name: "idx_a", Schema: "shop", Table: "orders",
				Columns: []string{"a", "b"}, Method: "btree",
			},
			want: "CREATE INDEX `idx_a` ON `shop`.`orders` (`a`, `b`);",
		},
		{
			name:   "primary key index has no standalone form",
			driver: DriverPostgres,
			in:     IndexInfo{Name: "users_pkey", Table: "users", Columns: []string{"id"}, IsPrimary: true},
			want:   "",
		},
		{
			name:   "expression-only index has no columns to render",
			driver: DriverPostgres,
			in:     IndexInfo{Name: "idx_expr", Table: "users"},
			want:   "",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := RenderCreateIndex(tc.driver, tc.in); got != tc.want {
				t.Errorf("RenderCreateIndex()\n got %q\nwant %q", got, tc.want)
			}
		})
	}
}

func TestJoinDDL(t *testing.T) {
	got := JoinDDL("CREATE TABLE a ();", "", "  \n", "CREATE INDEX i ON a (x);")
	want := "CREATE TABLE a ();\n\nCREATE INDEX i ON a (x);"
	if got != want {
		t.Errorf("JoinDDL() = %q, want %q", got, want)
	}
	if got := JoinDDL("", ""); got != "" {
		t.Errorf("JoinDDL of nothing = %q, want empty", got)
	}
}

func TestTerminateStatement(t *testing.T) {
	tests := []struct{ in, want string }{
		{"CREATE TABLE t (a int)", "CREATE TABLE t (a int);"},
		{"CREATE TABLE t (a int);", "CREATE TABLE t (a int);"},
		{"CREATE TABLE t (a int);\n\n", "CREATE TABLE t (a int);"},
		{"", ""},
		{"   \n ", ""},
	}
	for _, tc := range tests {
		if got := TerminateStatement(tc.in); got != tc.want {
			t.Errorf("TerminateStatement(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestQuoteIdentList(t *testing.T) {
	if got := QuoteIdentList(DriverPostgres, []string{"a", "b"}); got != `"a", "b"` {
		t.Errorf("QuoteIdentList() = %q", got)
	}
	if got := QuoteIdentList(DriverPostgres, nil); got != "" {
		t.Errorf("QuoteIdentList(nil) = %q, want empty", got)
	}
}

func TestRelationKind(t *testing.T) {
	tests := []struct {
		in   string
		want ObjectKind
	}{
		{"table", ObjectTable},
		{"view", ObjectView},
		{"VIEW", ObjectView},
		{"materialized view", ObjectMatView},
		{"partitioned table", ObjectTable},
		{"", ObjectTable},
	}
	for _, tc := range tests {
		if got := RelationKind(tc.in); got != tc.want {
			t.Errorf("RelationKind(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestObjectKindIsRelation(t *testing.T) {
	for _, k := range []ObjectKind{ObjectTable, ObjectView, ObjectMatView} {
		if !k.IsRelation() {
			t.Errorf("%q should be a relation", k)
		}
	}
	for _, k := range []ObjectKind{ObjectIndex, ObjectConstraint, ObjectTrigger, ObjectFunction, ObjectProcedure} {
		if k.IsRelation() {
			t.Errorf("%q should not be a relation", k)
		}
	}
}
