// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CSVOptions {
    /**
     * Delimiter is empty to sniff it. Quoting is always the CSV standard.
     */
    "delimiter"?: string;
    "hasHeader": boolean;

    /**
     * NullLiteral is extra text that becomes SQL NULL; a bare empty field already is.
     */
    "nullLiteral"?: string;

    /**
     * SkipRows drops leading lines before the header is read.
     */
    "skipRows"?: number;
    "trimSpace"?: boolean;

    /** Creates a new CSVOptions instance. */
    constructor($$source: Partial<CSVOptions> = {}) {
        if (!("hasHeader" in $$source)) {
            this["hasHeader"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CSVOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): CSVOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CSVOptions($$parsedSource as Partial<CSVOptions>);
    }
}
