// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appmenu$0 from "../appmenu/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendTextFile writes one chunk, emptying the file first when truncate is set. Each chunk opens and
 * closes the file, so nothing leaks if the caller stops part-way.
 */
export function AppendTextFile(path: string, chunk: string, truncate: boolean): $CancellablePromise<void> {
    return $Call.ByID(403815492, path, chunk, truncate);
}

/**
 * BeginTransaction pins a dedicated connection to the tab and opens a transaction.
 * Subsequent ExecuteQueryStream calls for tabID will run on that connection until
 * CommitTransaction or RollbackTransaction is called.
 */
export function BeginTransaction(connectionID: string, tabID: string): $CancellablePromise<void> {
    return $Call.ByID(2187422330, connectionID, tabID);
}

export function CancelQuery(connectionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3821899609, connectionID);
}

/**
 * CheckForUpdates opens the built-in update window and runs the full flow
 * (download, verify, Restart & Apply). Bound to the About dialog's button.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(74745528);
}

/**
 * CleanupTabTransaction rolls back any open transaction for the tab. Called when a tab is closed.
 */
export function CleanupTabTransaction(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(386939206, tabID);
}

export function ClearQueryHistory(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(3511871798, connectionID);
}

/**
 * CommitTransaction commits the open transaction on the tab and releases the pinned connection.
 */
export function CommitTransaction(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(1672899332, tabID);
}

export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(1546757449, id);
}

export function DeleteConnection(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3337158526, id);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(183030786, id);
}

export function DeleteQueryHistoryEntry(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3668220758, id);
}

export function DeleteRows(connectionID: string, del: database$0.RowDelete): $CancellablePromise<number> {
    return $Call.ByID(3419106895, connectionID, del);
}

export function DeleteSavedQuery(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2873411343, id);
}

export function DeleteSetting(key: string): $CancellablePromise<void> {
    return $Call.ByID(3413671862, key);
}

export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3864830715, id);
}

export function EmitMenuAction(id: string): $CancellablePromise<void> {
    return $Call.ByID(308134503, id);
}

export function EmitOpenSQLite(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(46205330, filePath);
}

export function ExecuteQuery(connectionID: string, sql: string): $CancellablePromise<database$0.QueryResult | null> {
    return $Call.ByID(1940384492, connectionID, sql).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ExecuteQueryStream(connectionID: string, tabID: string, sql: string): $CancellablePromise<void> {
    return $Call.ByID(3110751220, connectionID, tabID, sql);
}

/**
 * ExplainQuery returns a normalized plan for one statement. analyze executes the statement, so a
 * write runs inside a transaction that is always rolled back; a tab with an open transaction runs
 * there instead, matching where a plain Run would have.
 */
export function ExplainQuery(connectionID: string, tabID: string, sql: string, analyze: boolean): $CancellablePromise<database$0.QueryPlan | null> {
    return $Call.ByID(3996023304, connectionID, tabID, sql, analyze).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ExportResult(result: database$0.QueryResult, format: string): $CancellablePromise<string> {
    return $Call.ByID(1465290314, result, format);
}

export function FormatSQL(sql: string): $CancellablePromise<string> {
    return $Call.ByID(557421198, sql);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1631861786).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetConnectionStatus(connectionID: string): $CancellablePromise<database$0.ConnectionStatus> {
    return $Call.ByID(2880332169, connectionID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetEditorSession(): $CancellablePromise<storage$0.EditorSession> {
    return $Call.ByID(881302078).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetObjectDDL reads the catalog only, so it stays available on read-only connections.
 */
export function GetObjectDDL(connectionID: string, ref: database$0.ObjectRef): $CancellablePromise<string> {
    return $Call.ByID(3474183456, connectionID, ref);
}

export function GetPathDefaults(): $CancellablePromise<$models.PathDefaults> {
    return $Call.ByID(230484794).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetPendingFile(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(109090272).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetQueryHistory(connectionID: string, limit: number): $CancellablePromise<database$0.HistoryEntry[]> {
    return $Call.ByID(4033942967, connectionID, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetSettings(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(222085978).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Returns once the run is registered; import:progress and import:done carry the outcome.
 */
export function ImportCSV(connectionID: string, importID: string, req: $models.CSVImportRequest): $CancellablePromise<void> {
    return $Call.ByID(3870150748, connectionID, importID, req);
}

/**
 * Reports progress instead of a result tab per statement; a dump can hold thousands.
 */
export function ImportSQL(connectionID: string, importID: string, req: $models.SQLImportRequest): $CancellablePromise<void> {
    return $Call.ByID(2865009632, connectionID, importID, req);
}

export function InitStores(configDir: string): $CancellablePromise<void> {
    return $Call.ByID(1152712829, configDir);
}

export function InsertRow(connectionID: string, schema: string, table: string, values: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1655633052, connectionID, schema, table, values).then(($result: any) => {
        return $$createType11($result);
    });
}

export function IsConnected(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1544907504, id);
}

export function IsDesktopMode(): $CancellablePromise<boolean> {
    return $Call.ByID(3428830396);
}

export function ListColumns(connectionID: string, schema: string, table: string): $CancellablePromise<database$0.ColumnInfo[]> {
    return $Call.ByID(3118816600, connectionID, schema, table).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListConnections(): $CancellablePromise<database$0.ConnectionConfig[]> {
    return $Call.ByID(1654481338).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListConstraints(connectionID: string, schema: string, table: string): $CancellablePromise<database$0.ConstraintInfo[]> {
    return $Call.ByID(459667143, connectionID, schema, table).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ListFolders(): $CancellablePromise<storage$0.ConnectionFolder[]> {
    return $Call.ByID(1373072582).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ListIndexes(connectionID: string, schema: string, table: string): $CancellablePromise<database$0.IndexInfo[]> {
    return $Call.ByID(1696593423, connectionID, schema, table).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ListRoutines(connectionID: string, schema: string): $CancellablePromise<database$0.RoutineInfo[]> {
    return $Call.ByID(1660715140, connectionID, schema).then(($result: any) => {
        return $$createType23($result);
    });
}

export function ListSavedQueries(connectionID: string): $CancellablePromise<database$0.SavedQuery[]> {
    return $Call.ByID(2254370512, connectionID).then(($result: any) => {
        return $$createType25($result);
    });
}

export function ListSchemas(connectionID: string): $CancellablePromise<database$0.SchemaInfo[]> {
    return $Call.ByID(2969331507, connectionID).then(($result: any) => {
        return $$createType27($result);
    });
}

export function ListTables(connectionID: string, schema: string): $CancellablePromise<database$0.TableInfo[]> {
    return $Call.ByID(773846824, connectionID, schema).then(($result: any) => {
        return $$createType29($result);
    });
}

export function ListTriggers(connectionID: string, schema: string, table: string): $CancellablePromise<database$0.TriggerInfo[]> {
    return $Call.ByID(1037368812, connectionID, schema, table).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * LoadSchemaData preloads tables for the default browse schema; Postgres also preloads "public"
 * so the schema browser is populated even when the default is a custom schema.
 */
export function LoadSchemaData(connectionID: string): $CancellablePromise<database$0.SchemaBundle> {
    return $Call.ByID(4233994986, connectionID).then(($result: any) => {
        return $$createType32($result);
    });
}

export function PickExportSavePath(ext: string): $CancellablePromise<string> {
    return $Call.ByID(1154457340, ext);
}

export function PickImportFile(kind: string): $CancellablePromise<string> {
    return $Call.ByID(452154835, kind);
}

export function PickKnownHostsFile(): $CancellablePromise<string> {
    return $Call.ByID(155068216);
}

export function PickSQLiteFile(): $CancellablePromise<string> {
    return $Call.ByID(2769801138);
}

export function PickSSHKeyFile(): $CancellablePromise<string> {
    return $Call.ByID(4136702487);
}

export function PreviewImportFile(connectionID: string, path: string, opts: service$0.CSVOptions): $CancellablePromise<$models.ImportPreview> {
    return $Call.ByID(2193346560, connectionID, path, opts).then(($result: any) => {
        return $$createType33($result);
    });
}

export function QueryTableStream(connectionID: string, tabID: string, req: database$0.TableDataRequest): $CancellablePromise<void> {
    return $Call.ByID(3607474293, connectionID, tabID, req);
}

export function ReorderConnections(orderedIDs: string[]): $CancellablePromise<boolean> {
    return $Call.ByID(2307732985, orderedIDs);
}

/**
 * RollbackTransaction rolls back the open transaction on the tab and releases the pinned connection.
 */
export function RollbackTransaction(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(546324027, tabID);
}

export function SaveConnection(cfg: database$0.ConnectionConfig): $CancellablePromise<database$0.ConnectionConfig> {
    return $Call.ByID(571429232, cfg).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SaveEditorSession(session: storage$0.EditorSession): $CancellablePromise<void> {
    return $Call.ByID(3313325587, session);
}

export function SaveFolder(f: storage$0.ConnectionFolder): $CancellablePromise<storage$0.ConnectionFolder> {
    return $Call.ByID(1026390748, f).then(($result: any) => {
        return $$createType18($result);
    });
}

export function SaveSavedQuery(q: database$0.SavedQuery): $CancellablePromise<database$0.SavedQuery> {
    return $Call.ByID(1936361457, q).then(($result: any) => {
        return $$createType24($result);
    });
}

export function SaveTextFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3576490577, path, content);
}

/**
 * SetNativeMenu hands over the macOS menu bar; its sync listener attaches in ServiceStartup.
 */
export function SetNativeMenu(menu: appmenu$0.Menu | null): $CancellablePromise<void> {
    return $Call.ByID(3893583927, menu);
}

export function SetOnSettingChanged(fn: any): $CancellablePromise<void> {
    return $Call.ByID(23377614, fn);
}

export function SetPendingFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(2899318644, path);
}

/**
 * SetSetting persists one preference; keys (e.g. "xensql-theme") are opaque here.
 */
export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2719370137, key, value);
}

export function SetWindowStateFlush(flush: any): $CancellablePromise<void> {
    return $Call.ByID(844868674, flush);
}

export function SettingsStore(): $CancellablePromise<storage$0.SettingsStore | null> {
    return $Call.ByID(2329735545).then(($result: any) => {
        return $$createType35($result);
    });
}

export function TestConnection(cfg: database$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(1803584041, cfg);
}

/**
 * TransactionStatus returns whether the given tab has an active transaction.
 */
export function TransactionStatus(tabID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3593372869, tabID);
}

export function UpdateRow(connectionID: string, upd: database$0.RowUpdate): $CancellablePromise<void> {
    return $Call.ByID(1118365152, connectionID, upd);
}

// Private type creation functions
const $$createType0 = database$0.QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = database$0.QueryPlan.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.AppInfo.createFrom;
const $$createType5 = database$0.ConnectionStatus.createFrom;
const $$createType6 = storage$0.EditorSession.createFrom;
const $$createType7 = $models.PathDefaults.createFrom;
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = database$0.HistoryEntry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = database$0.ColumnInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = database$0.ConnectionConfig.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = database$0.ConstraintInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = storage$0.ConnectionFolder.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = database$0.IndexInfo.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = database$0.RoutineInfo.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = database$0.SavedQuery.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = database$0.SchemaInfo.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = database$0.TableInfo.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = database$0.TriggerInfo.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = database$0.SchemaBundle.createFrom;
const $$createType33 = $models.ImportPreview.createFrom;
const $$createType34 = storage$0.SettingsStore.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
