// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppInfo {
    "name": string;
    "version": string;
    "author": string;
    "email": string;
    "website": string;
    "repository": string;
    "description": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("website" in $$source)) {
            this["website"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

/**
 * PathDefaults lets the UI show example paths that match the host, not one platform's convention.
 */
export class PathDefaults {
    "platform": string;
    "separator": string;

    /**
     * SSHKey and SSHKnownHosts are empty when the home directory cannot be resolved.
     */
    "sshKey"?: string;
    "sshKnownHosts"?: string;

    /** Creates a new PathDefaults instance. */
    constructor($$source: Partial<PathDefaults> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("separator" in $$source)) {
            this["separator"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathDefaults instance from a string or object.
     */
    static createFrom($$source: any = {}): PathDefaults {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathDefaults($$parsedSource as Partial<PathDefaults>);
    }
}
